version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    working_dir: /var/lib/redis
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/var/lib/redis/data
    command: redis-server /usr/local/etc/redis/redis.conf

  sidekiq:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=development
      - RACK_ENV=development
      - NODE_ENV=development
    volumes:
      - .:/app
    command: bundle exec sidekiq -C config/sidekiq.yml

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=development
      - RACK_ENV=development
      - NODE_ENV=development
    volumes:
      - .:/app
    command: bundle exec rails server -b 0.0.0.0

volumes:
  database_data:
  redis_data:
