version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  delayed_job:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - RAILS_ENV=development
      - RACK_ENV=development
      - NODE_ENV=development
    volumes:
      - .:/app
    command: bundle exec rake jobs:work

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - delayed_job
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - RAILS_ENV=development
      - RACK_ENV=development
      - NODE_ENV=development
    volumes:
      - .:/app
    command: bundle exec rails server -b 0.0.0.0

volumes:
  database_data:
